name: Release Deploy

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: [self-hosted, deploy-release]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Build
        run: docker build . --file Dockerfile --tag xivrepo/apiserver-release:${{ github.sha }}

      -
        name: Deploy
        run: |
          pushd /compose/release-api-server
          TAG=${{ github.sha }} docker-compose up -d
          popd
